import type { Metadata } from 'next';
import './globals.scss';
import QueryProvider from './queryProvider';
import BrowserProvider from '@/providers/BrowserProvider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body>
        <BrowserProvider>
          <QueryProvider>{children}</QueryProvider>
        </BrowserProvider>
      </body>
    </html>
  );
}
